test_mode: true
session:
  max_iterations: 100
  max_runtime_hours: 1
mcts:
  max_tree_depth: 15
  expansion_budget: 1
autogluon:
  dataset_name: titanic-mcts-test
  target_column: survived
  target_metric: accuracy
  included_model_types:
  - XGB
  time_limit: 60
  verbosity: 2
feature_space:
  max_features_per_node: 300
  max_cache_size_mb: 2048
resources:
  max_memory_gb: 1
  max_cpu_cores: 2
logging:
  log_level: INFO
  max_log_size_mb: 10