test_mode: false
session:
  max_iterations: 100
  max_runtime_hours: 24
autogluon:
  dataset_name: playground-series-s5e6-2025
  target_metric: MAP@3
  included_model_types:
  - XGB
  - GBM
  - CAT
  - NN_TORCH
  train_size: 0.8
  time_limit: 60
  presets: best_quality
  num_bag_folds: 5
  num_bag_sets: 2
feature_space:
  max_features_per_node: 500
  min_improvement_threshold: 0.0001
  generic_operations:
    statistical_aggregations: true
    polynomial_features: true
    binning_features: true
    ranking_features: true
  generic_params:
    polynomial_degree: 3
    binning_bins: 10
    groupby_columns: []
    aggregate_columns: []
  '# NOTE': Categories are now discovered dynamically from operation metadata
  use_dynamic_categories: true
  category_filter:
    include:
    - binning
    - categorical
    - polynomial
    - ranking
    - statistical
    - temporal
    - text
    exclude: []
  category_weights:
    binning: 1.0
    categorical: 1.1
    polynomial: 0.8
    ranking: 0.9
    statistical: 1.0
    temporal: 0.7
    text: 0.6
  '# DYNAMIC_CATEGORIES_INFO': Categories and weights are generated from src/features/generic/OPERATION_METADATA
logging:
  level: INFO
  log_feature_code: true
  log_timing: true
  log_memory_usage: true
  progress_interval: 5
export:
  formats:
  - python
  - json
  - html
  python_output: outputs/s5e6_best_features_production.py
  html_report: outputs/s5e6_discovery_report_production.html
  output_dir: outputs/reports_production
