test_mode: false
session:
  max_iterations: 3
  max_runtime_hours: 0.1
  checkpoint_interval: 1
mcts:
  exploration_weight: 1.4
  max_tree_depth: 3
  expansion_threshold: 1
  min_visits_for_best: 1
  max_children_per_node: 3
  expansion_budget: 3
  max_nodes_in_memory: 1000
autogluon:
  dataset_name: titanic
  target_metric: accuracy
  ignore_columns: null
  included_model_types:
  - XGB
  enable_gpu: true
  train_size: 100
  time_limit: 30
  presets: medium_quality
  skip_final_evaluation: true
  holdout_frac: 0.2
  verbosity: 1
  ag_args_fit:
    num_cpus: 1
    num_gpus: 1
  ag_args_ensemble:
    fold_fitting_strategy: sequential_local
    enable_ray: false
feature_space:
  max_features_per_node: 20
  feature_timeout: 30
  max_cache_size_mb: 256
  max_features_to_build: 5
  max_features_per_iteration: 2
  feature_build_timeout: 30
  cache_miss_limit: 5
  generic_operations:
    statistical_aggregations: true
    polynomial_features: false
    binning_features: true
    ranking_features: false
  generic_params:
    binning_bins: 3
    groupby_columns:
    - Sex
    aggregate_columns:
    - Age
  category_weights:
    binning: 1.0
    categorical: 1.1
    polynomial: 0.8
    ranking: 0.9
    statistical: 1.0
    temporal: 0.7
    text: 0.6
  '# DYNAMIC_CATEGORIES_INFO': Categories and weights are generated from src/features/generic/OPERATION_METADATA
resources:
  max_memory_gb: 1
  memory_check_interval: 1
  force_gc_interval: 5
  max_cpu_cores: 2
  max_disk_usage_gb: 5
data:
  backend: duckdb
  prefer_parquet: false
  auto_convert_csv: false
  memory_limit_mb: 256
  dtype_optimization: true
database:
  path: data/minotaur.duckdb
  max_history_size: 1000
  backup_interval: 10
  retention_days: 1
logging:
  level: DEBUG
  max_log_size_mb: 50
  progress_interval: 1
  log_autogluon_details: false
  log_mcts_details: true
  log_feature_generation: true
  log_database_operations: true
export:
  formats: []
  include_documentation: false
  output_dir: outputs/debug_test
  export_on_improvement: false
  export_on_completion: false
analytics:
  generate_charts: false
  include_timing_analysis: true
validation:
  validate_generated_features: false
