autogluon:
  dataset_name: titanic
  target_column: Survived
  id_column: PassengerId
  target_metric: accuracy
  train_size: 0.8
  time_limit: 60
  included_model_types:
  - RF
  - GBM
  - XT
  hyperparameters: light
  enable_gpu: false
  sample_weight_column: null
  ignore_columns: []
mcts:
  exploration_weight: 1.4
  max_tree_depth: 5
  expansion_threshold: 1
  max_children_per_node: 10
  expansion_budget: 50
  max_nodes_in_memory: 1000
  prune_threshold: 0.01
session:
  max_iterations: 100
  max_runtime_hours: 0.5
  checkpoint_interval: 20
  enable_checkpoints: true
feature_space:
  use_new_pipeline: true
  check_signal: true
  min_signal_ratio: 0.01
  signal_sample_size: 500
  lowercase_features: false
  apply_generic_to_custom: true
  cache_features: true
  cache_intermediate: false
  max_features_per_type: null
  max_features_per_node: 200
  category_weights:
    binning: 1.0
    categorical: 1.1
    polynomial: 0.8
    ranking: 0.9
    statistical: 1.0
    temporal: 0.7
    text: 0.6
  generic_params:
    groupby_columns:
    - Sex
    - Pclass
    - Embarked
    aggregate_columns:
    - Age
    - Fare
    - SibSp
    - Parch
    polynomial_degree: 2
    binning_bins: 5
  generic_operations:
    statistical_aggregations: true
    polynomial_features: true
    binning_features: true
    ranking_features: true
    categorical_features: true
    temporal_features: false
    text_features: true
  '# NOTE': Categories are now discovered dynamically from operation metadata
  use_dynamic_categories: true
  category_filter:
    include:
    - binning
    - categorical
    - polynomial
    - ranking
    - statistical
    - temporal
    - text
    exclude: []
  '# DYNAMIC_CATEGORIES_INFO': Categories and weights are generated from src/features/generic/OPERATION_METADATA
resources:
  max_memory_gb: 8
  max_threads: 4
  force_gc_interval: 50
logging:
  level: INFO
  progress_interval: 10
  show_memory_usage: true
  log_feature_generation: true
data:
  duckdb:
    max_memory_gb: 4
    enable_sampling: true
