# MCTS Feature Discovery - Fast Test Overrides
# This file contains only parameters that override the main mcts_config.yaml
# For ultra-fast testing with real AutoGluon on minimal datasets
#
# PERFORMANCE TARGET: Complete 3 iterations in 30-60 seconds
# RESOURCE LIMITS: 1K samples, minimal memory, XGBoost only

# Session Management - Ultra-short runs
session:
  max_iterations: 3              # Ultra-short for testing
  max_runtime_hours: 0.25        # 15 minutes max
  checkpoint_interval: 1         # Save every iteration

# MCTS - Minimal exploration
mcts:
  max_tree_depth: 4             # Very shallow
  expansion_threshold: 1        # Expand immediately
  min_visits_for_best: 2        # Minimal visits
  max_children_per_node: 2      # Very few children
  expansion_budget: 5           # Tiny budget
  max_nodes_in_memory: 1000     # Minimal memory

# AutoGluon - Ultra-fast evaluation
autogluon:
  # Core configuration - extreme speed focus
  included_model_types: ['XGB']           # Only XGBoost
  enable_gpu: true                        # GPU for speed
  train_size: 0.02                        # Only 2% of training data
  
  # Model training settings
  time_limit: 8                           # Extremely short evaluation
  presets: 'medium_quality_faster_train'  # Fast preset
  num_bag_folds: 1                        # No bagging for speed
  num_bag_sets: 1                         # Single bagging set
  holdout_frac: 0.4                       # Large holdout for speed
  verbosity: 0                            # Silent mode

# Feature Space - Minimal features
feature_space:
  max_features_per_node: 50               # Very few features
  feature_timeout: 30                     # Short timeout
  max_cache_size_mb: 256                  # Tiny cache
  
  # Only most effective categories
  enabled_categories:
    - 'npk_interactions'                  # Essential only
    - 'agricultural_domain'
    
  # Focused weights
  category_weights:
    npk_interactions: 3.0                 # High priority
    agricultural_domain: 3.0              # High priority

# Performance - Minimal resources
resources:
  max_memory_gb: 1                        # Very low memory
  memory_check_interval: 1                
  force_gc_interval: 5                    # Very frequent GC
  max_cpu_cores: 2                        # Limit CPU cores
  max_disk_usage_gb: 5                    # Minimal disk

# Data - Ultra-small datasets
data:
  prefer_parquet: true                    # Fast loading
  auto_convert_csv: true                  
  use_small_dataset: true                 
  small_dataset_size: 1000                # Only 1K samples
  memory_limit_mb: 50                     # Very low memory limit
  dtype_optimization: true                

# Database - Minimal settings
database:
  path: '../data/feature_discovery_test.db'      # Separate test DB
  max_history_size: 1000                  # Tiny history
  backup_interval: 10                     # Frequent backups
  retention_days: 1                       # Very short retention

# Logging - Minimal for speed
logging:
  log_file: '../logs/mcts_discovery_test.log'    # Separate test log
  max_log_size_mb: 10                     # Small logs
  progress_interval: 1                    # Report every iteration
  log_autogluon_details: false           # Skip details

# Testing - Minimal datasets
testing:
  small_dataset_size: 1000                # Match data.small_dataset_size
  use_mock_evaluator: false               # Use real AutoGluon

# Export - Minimal output
export:
  formats: ['python']                     # Only Python code
  python_output: '../outputs/best_features_test.py'
  include_documentation: false            
  output_dir: '../outputs/reports_test'
  export_on_improvement: false            # Skip intermediate
  export_on_completion: true              # Only final export

# Analytics - Skip for speed
analytics:
  generate_charts: false                  # No charts for speed
  include_timing_analysis: false          # Skip timing analysis

# Validation - Skip for speed
validation:
  validate_generated_features: false      # Skip validation