# MCTS Configuration Override for Playground Series S5E6 - Fast Real Testing
# This file contains only parameters that override the main mcts_config.yaml
# For rapid iteration with real AutoGluon on reduced datasets
#
# PERFORMANCE TARGET: Complete 5 iterations in 2-5 minutes
# RESOURCE LIMITS: 5K samples, reduced memory, focused on XGBoost

# Session Management - Shorter runs
session:
  max_iterations: 5              # Very short for fast iteration
  max_runtime_hours: 1           # Short runtime
  checkpoint_interval: 2         # Frequent saves

# MCTS - Faster exploration
mcts:
  max_tree_depth: 6             # Reduced depth
  expansion_threshold: 2        # Lower threshold
  min_visits_for_best: 5        # Reduced minimum
  max_children_per_node: 3      # Fewer children
  expansion_budget: 10          # Smaller budget
  max_nodes_in_memory: 5000     # Reduced memory

# AutoGluon - Fast evaluation with XGBoost focus
autogluon:
  # S5E6 Dataset paths
  train_path: "/mnt/ml/competitions/2025/playground-series-s5e6/train.csv"
  test_path: "/mnt/ml/competitions/2025/playground-series-s5e6/test.csv"
  target_metric: 'MAP@3'
  
  # Core configuration - focus on speed
  included_model_types: ['XGB']           # Only XGBoost
  enable_gpu: true                        # GPU acceleration
  train_size: 0.05                        # 5% of training data for very fast testing
  
  # Model training settings
  time_limit: 30                          # Seconds per evaluation
  presets: 'medium_quality_faster_train'  # Fast preset
  num_bag_folds: 1                        # Minimal bagging for speed
  num_bag_sets: 1                         # Single bagging set
  holdout_frac: 0.3                       # Larger holdout for speed
  verbosity: 0                            # Silent mode for speed

# Feature Space - Focused categories for fertilizer domain
feature_space:
  domain_module: 'domains.fertilizer_s5e6'
  enabled_categories:
    - 'npk_interactions'
    - 'agricultural_domain'
  max_features_per_node: 150              # Reduced feature count
  feature_timeout: 120                    # Shorter timeout
  max_cache_size_mb: 1024                 # Reduced cache

# Performance - Resource limits
resources:
  max_memory_gb: 2                        # Low memory limit
  memory_check_interval: 2                
  force_gc_interval: 10                   # Frequent GC
  max_cpu_cores: 4                        # Limit CPU cores
  max_disk_usage_gb: 10                   # Reduced disk

# Data - Fast loading optimizations
data:
  prefer_parquet: true                    # Always use parquet
  auto_convert_csv: true                  # Auto convert
  memory_limit_mb: 100                    # Low memory limit
  dtype_optimization: true                # Optimize types

# Database - Smaller limits
database:
  path: 'data/feature_discovery_fast.db'      # Separate DB
  max_history_size: 10000                 # Smaller history
  backup_interval: 25                     # More frequent
  retention_days: 7                       # Shorter retention

# Logging - Faster reporting
logging:
  log_file: 'logs/mcts_discovery_fast.log'    # Separate log
  max_log_size_mb: 50                     # Smaller logs
  progress_interval: 5                    # More frequent progress

# Testing - Mock evaluator settings
testing:
  fast_test_mode: false                   # Real AutoGluon mode

# Export - Minimal for speed
export:
  formats: ['python', 'json']             # Skip HTML
  python_output: 'outputs/s5e6_best_features_fast_real.py'
  include_documentation: false            # Skip docs
  output_dir: 'outputs/reports_fast_real'
  export_on_improvement: false            # Skip intermediate exports

# Analytics - Minimal
analytics:
  figure_size: [10, 6]                    # Smaller figures
  dpi: 72                                 # Lower DPI