test_mode: false
session:
  mode: new
  max_iterations: 20
  max_runtime_hours: 12
  checkpoint_interval: 25
  auto_save: true
  session_name: null
mcts:
  exploration_weight: 1.4
  max_tree_depth: 8
  expansion_threshold: 3
  min_visits_for_best: 10
  ucb1_confidence: 0.95
  selection_strategy: ucb1
  max_children_per_node: 5
  expansion_budget: 20
  max_nodes_in_memory: 10000
  prune_threshold: 0.1
autogluon:
  dataset_name: null
  target_metric: null
  included_model_types:
  - XGB
  - GBM
  - CAT
  enable_gpu: true
  train_size: 0.8
  time_limit: 60
  presets: medium_quality
  num_bag_folds: 3
  num_bag_sets: 1
  holdout_frac: 0.2
  verbosity: 1
feature_space:
  max_features_per_node: 300
  min_improvement_threshold: 0.0005
  feature_timeout: 300
  max_features_to_build: null
  max_features_per_iteration: null
  feature_build_timeout: 300
  cache_miss_limit: 50
  generic_operations:
    statistical_aggregations: true
    polynomial_features: true
    binning_features: true
    ranking_features: true
    categorical_features: true    # Re-enabled with NA fix
    text_features: true          # Re-enabled 
    train_features: true         # Re-enabled
  generic_params:
    polynomial_degree: 2
    binning_bins: 5
    groupby_columns: []
    aggregate_columns: []
  category_weights:
    binning: 1.0
    categorical: 1.1
    polynomial: 0.8
    ranking: 0.9
    statistical: 1.0
    temporal: 0.7
    text: 0.6
  lazy_loading: true
  cache_features: true
  max_cache_size_mb: 2048
  cache_cleanup_threshold: 0.8
  '# NOTE': Categories are now discovered dynamically from operation metadata
  use_dynamic_categories: true
  category_filter:
    include:
    - binning
    - categorical
    - polynomial
    - ranking
    - statistical
    - temporal
    - text
    exclude: []
  '# DYNAMIC_CATEGORIES_INFO': Categories and weights are generated from src/features/generic/OPERATION_METADATA
database:
  path: data/minotaur.duckdb
  type: duckdb
  schema: main
  backup_path: data/backups/
  backup_interval: 50
  backup_prefix: minotaur_backup_
  max_history_size: 50000
  max_backup_files: 10
  batch_size: 10
  sync_mode: NORMAL
  journal_mode: WAL
  auto_cleanup: true
  cleanup_interval_hours: 24
  retention_days: 30
logging:
  level: DEBUG
  log_file: logs/minotaur.log
  max_log_size_mb: 100
  backup_count: 5
  log_feature_code: true
  log_timing: true
  log_memory_usage: true
  log_autogluon_details: false
  progress_interval: 10
  save_intermediate_results: true
  timing_output_dir: logs/timing
resources:
  max_memory_gb: 16
  memory_check_interval: 5
  force_gc_interval: 50
  use_gpu: true
  max_cpu_cores: -1
  autogluon_num_cpus: null
  max_disk_usage_gb: 50
  temp_dir: /tmp/mcts_features
  cleanup_temp_on_exit: true
data:
  backend: auto
  prefer_parquet: true
  auto_convert_csv: true
  dtype_optimization: true
  memory_limit_mb: 500
  use_small_dataset: false
  small_dataset_size: 5000
  duckdb:
    enable_sampling: true
    max_memory_gb: 4
    temp_directory: /tmp/duckdb_temp
    use_memory_limit: true
    persistent_storage: true
    database_name: features.duckdb
    auto_load_data: true
    enable_feature_cache: true
    max_cached_features: 1000
    cache_cleanup_threshold: 0.8
    cache_min_score: 0.1
    enable_object_cache: true
    force_compression: zstd
    enable_progress_bar: false
llm:
  enabled: false
  provider: openai
  model: gpt-4
  api_key_env: OPENAI_API_KEY
  trigger_interval: 20
  trigger_on_plateau: true
  plateau_threshold: 15
  max_features_per_request: 5
  temperature: 0.7
  max_tokens: 1000
export:
  formats:
  - python
  - json
  - html
  python_output: outputs/best_features_discovered.py
  include_dependencies: true
  include_documentation: true
  code_style: pep8
  html_report: outputs/discovery_report.html
  include_plots: true
  plot_format: png
  include_analytics: true
  output_dir: outputs/reports
  export_on_completion: true
  export_on_improvement: true
  export_interval: 100
analytics:
  figure_size:
  - 12
  - 8
  dpi: 100
  format: png
  generate_charts: true
  include_timing_analysis: true
validation:
  validate_generated_features: true
  max_validation_time: 60
  cv_folds: 3
  cv_repeats: 1
  significance_level: 0.05
  min_samples_for_test: 10
advanced:
  enable_neural_mcts: false
  enable_parallel_evaluation: false
  enable_multi_objective: false
  debug_mode: false
  debug_save_all_features: false
  debug_detailed_timing: false
  auto_recovery: true
  max_recovery_attempts: 3
  recovery_checkpoint_interval: 10
