# MCTS Configuration Override for Playground Series S5E6 - Production
# This config inherits from mcts_config.yaml and overrides for production fertilizer prediction

# Session settings for production
session:
  max_iterations: 100
  max_runtime_hours: 24

# Production AutoGluon configuration
autogluon:
  dataset_name: 'playground-series-s5e6-2025'
  target_metric: 'MAP@3'
  
  # Full model ensemble for production
  included_model_types: ['XGB', 'GBM', 'CAT', 'NN_TORCH']
  train_size: 0.8
  time_limit: 300
  presets: 'best_quality'
  num_bag_folds: 5
  num_bag_sets: 2

# Feature space configuration for fertilizer domain
feature_space:
  domain_module: 'domains.fertilizer_s5e6'
  enabled_categories:
    - 'npk_interactions'
    - 'environmental_stress'
    - 'agricultural_domain'
    - 'statistical_aggregations'
    - 'feature_transformations'
  
  # Higher limits for production
  max_features_per_node: 500
  min_improvement_threshold: 0.0001
  
  # Generic operations - all enabled for production exploration
  generic_operations:
    statistical_aggregations: true     # Enable all aggregations
    polynomial_features: true         # Enable polynomial features
    binning_features: true            # Enable binning
    ranking_features: true            # Enable ranking features
  
  # Generic operation parameters - production settings
  generic_params:
    polynomial_degree: 3              # Higher degree for more features
    binning_bins: 10                  # More bins for finer discretization
    groupby_columns: []               # Auto-detect all categorical columns
    aggregate_columns: []             # Auto-detect all numeric columns

# Logging configuration for production
logging:
  level: 'INFO'
  log_feature_code: true
  log_timing: true
  log_memory_usage: true
  progress_interval: 5

# Export configuration
export:
  formats: ['python', 'json', 'html']
  python_output: 'outputs/s5e6_best_features_production.py'
  html_report: 'outputs/s5e6_discovery_report_production.html'
  output_dir: 'outputs/reports_production'