test_mode: false
session:
  max_iterations: 5
  max_runtime_hours: 1
  checkpoint_interval: 2
mcts:
  max_tree_depth: 6
  expansion_threshold: 2
  min_visits_for_best: 5
  max_children_per_node: 3
  expansion_budget: 10
  max_nodes_in_memory: 5000
autogluon:
  dataset_name: playground-series-s5e6-2025
  target_metric: MAP@3
  included_model_types:
  - XGB
  enable_gpu: true
  train_size: 0.05
  time_limit: 60
  presets: medium_quality_faster_train
  num_bag_folds: 1
  num_bag_sets: 1
  holdout_frac: 0.3
  verbosity: 0
feature_space:
  max_features_per_node: 150
  feature_timeout: 120
  max_cache_size_mb: 1024
  generic_operations:
    statistical_aggregations: true
    polynomial_features: true
    binning_features: true
    ranking_features: false
  generic_params:
    polynomial_degree: 2
    binning_bins: 5
    groupby_columns: []
    aggregate_columns: []
  '# NOTE': Categories are now discovered dynamically from operation metadata
  use_dynamic_categories: true
  category_filter:
    include:
    - binning
    - categorical
    - polynomial
    - ranking
    - statistical
    - temporal
    - text
    exclude: []
  category_weights:
    binning: 1.0
    categorical: 1.1
    polynomial: 0.8
    ranking: 0.9
    statistical: 1.0
    temporal: 0.7
    text: 0.6
  '# DYNAMIC_CATEGORIES_INFO': Categories and weights are generated from src/features/generic/OPERATION_METADATA
resources:
  max_memory_gb: 2
  memory_check_interval: 2
  force_gc_interval: 10
  max_cpu_cores: 4
  max_disk_usage_gb: 10
data:
  prefer_parquet: true
  auto_convert_csv: true
  memory_limit_mb: 100
  dtype_optimization: true
database:
  path: data/feature_discovery_fast.db
  max_history_size: 10000
  backup_interval: 25
  retention_days: 7
logging:
  log_file: logs/mcts_discovery_fast.log
  max_log_size_mb: 50
  progress_interval: 5
export:
  formats:
  - python
  - json
  python_output: outputs/s5e6_best_features_fast_real.py
  include_documentation: false
  output_dir: outputs/reports_fast_real
  export_on_improvement: false
analytics:
  figure_size:
  - 10
  - 6
  dpi: 72
